# Site settings

#titles
title: Edinei Fedel
author_title: Software Developer
home_title: Home
about_title: About

#url
# url: http://edineifedel.com

#bio
author: Edinei Fedel
author_photo: profile-photo.jpg

user_description: |
  My name is Edinei Fedel and I am a proud father, man of faith, and passionate technologist from Brazil.
  
  I'm envolved with the web since early 2000s. My first website was a static monstruosity on a free hosting server. Since then I've learned a lot of programming languages and technologies, mostly specializing in JVM.
  
  Outside of programming I enjoy playing bass, making beer and drinking coffee.

# tags social links
email: edineifedel@gmail.com
linkedin: edinei-fedel-845b5228
github: edineifedel
twitter: edineifedel
facebook: edineifedel

## Disqus
disqus_identifier: edineifedel

## Tracker
google_analytics_id: UA-157541538-1

keywords: 'software,developer,design,java,javascript,bass,music,edinei fedel,fedel'

## URLs
permalink: ':title/'
baseurl: ''
home_url: '/'
about_url: '/about'

plugins:
  - jekyll-feed

exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'README.md']

# sass:
#   style: compressed